### ISSUE TITLE
窗口大小可调就好 了

### ISSUE THREAD

**Issue by xs-alpha** [zhangqi-ulua/ConvertTools#1]
我是双屏幕，这一个软件打开一个屏放不下，希望窗口可以小一点，拖动的时候任务栏会闪烁跳动，

**Comment by zhangqi-ulua** [comment]
现在多数电脑屏幕都能达到1920*1080的分辨率了。左边功能比较多，再小也放不下了。如果屏幕分辨率比较低的话。最好还是下载个vistual studio，手工调小一下窗口和字体大小吧。软件还是以多数人的屏幕适配
