### ISSUE TITLE
[BUG]解码BASE64程序崩了

### ISSUE THREAD

**Issue by AmyCoa** [zhangqi-ulua/ConvertTools#3]
![屏幕截图_20241104213647](https://github.com/user-attachments/assets/1c8de658-13a0-46a8-83a5-60007f37c719)
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at ConvertTools.Utils.EncodeUtil.Base64Decode(String text)
   at ConvertTools.MainForm.BtnBase64Decode_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Private.CoreLib.dll
----------------------------------------
ConvertTools
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///C:/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E7%BC%96%E7%A0%81%E8%A7%A3%E7%A0%81/ConvertTools.dll
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.2623.60505
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.26/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.2623.60505
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.26/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Collections.dll
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.26/System.Drawing.Common.dll
----------------------------------------
System.Text.Encoding.CodePages
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Text.Encoding.CodePages.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.2623.60505
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.26/Accessibility.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Numerics.Vectors.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Memory.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.2623.60505
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.26/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.26/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.ObjectModel.dll
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Linq.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Private.Uri.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.2623.60508
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.26/System.Collections.Immutable.dll
----------------------------------------

************** JIT 调试 **************

**Comment by AmyCoa** [comment]
![屏幕截图_20241104213853](https://github.com/user-attachments/assets/0df0e6ef-d412-4b78-beed-4918ae1fb073)

**Comment by zhangqi-ulua** [comment]
是的，这块没try-catch处理。对于错误的base64字符串，会报错
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
